version: '3'

services:

    app:
        build: .
        container_name: pdf-manager-app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        depends_on:
            - db

    db:
        build: ./.docker/mysql
        container_name: pdf-manager-db
        restart: always
        tty: true
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_DATABASE=pdf_manager
    
    selenium:
        image: selenium/standalone-chrome
        expose:
           - 4444