version: '3'

services:

    app:
        build: .
        entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www